[package]
name = "zrglng"
version = "0.1.0"
authors = ["Justin Rerolle <justin.rerolle@sap.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper" }
tokio = { git = "https://github.com/tokio-rs/tokio" }
